# Generated by Django 4.1 on 2023-05-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleframe',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicleframe',
            name='video_frame',
        ),
        migrations.AddField(
            model_name='vehicleframe',
            name='image',
            field=models.ImageField(default=0, upload_to='vehicle_imgs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleframe',
            name='track_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleframe',
            name='video_filename',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicleframe',
            name='video_frame_cnt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleframe',
            name='x1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleframe',
            name='x2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleframe',
            name='y1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleframe',
            name='y2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
