# Generated by Django 4.1 on 2023-05-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_remove_vehicleframe_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleframe',
            name='image',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='track_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='video_filename',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
