# Generated by Django 4.1 on 2023-05-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_remove_vehicleframe_image_vehicle_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='video',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
