# Generated by Django 4.1 on 2023-05-16 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_brand', models.CharField(max_length=20, null=True)),
                ('drone_model', models.CharField(max_length=20, null=True)),
                ('drone_magnification', models.FloatField(default=1.33, null=True)),
                ('users', models.ManyToManyField(related_name='drones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drone',
                'verbose_name_plural': 'Drones',
                'db_table': 'drone',
            },
        ),
    ]
