# Generated by Django 4.1 on 2023-05-16 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_filename', models.FileField(upload_to='videos/')),
                ('x_resolution', models.IntegerField(default=3840, null=True)),
                ('y_resolution', models.IntegerField(default=2160, null=True)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('video_latitude', models.FloatField(null=True)),
                ('video_longitude', models.FloatField(null=True)),
                ('drone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drone.drone')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_frame_cnt', models.IntegerField()),
                ('frame_diff_time', models.IntegerField(null=True)),
                ('frame_datetime', models.DateTimeField(null=True)),
                ('frame_altitude', models.IntegerField(null=True)),
                ('frame_latitude', models.FloatField(null=True)),
                ('frame_longitude', models.FloatField(null=True)),
                ('frame_dzoom_ratio', models.IntegerField(null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
    ]
