# Generated by Django 4.1 on 2023-05-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_filename',
            field=models.FileField(unique=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videoframe',
            name='frame_altitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='videoframe',
            name='frame_dzoom_ratio',
            field=models.FloatField(null=True),
        ),
    ]
